# Generated by Django 3.1.4 on 2022-08-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
